name: LLVM Toolchain
on: 
  workflow_dispatch:
  schedule:
    - cron:  '0 17 * * 3'

jobs:
  build:
    runs-on: ubuntu-latest
    environment: Actions
    steps:
      - name: Download scripts
        uses: actions/checkout@v3

      - name: Get deps
        run: ./ci.sh deps

      - name: Get deps
        run: ./build-tc.sh
